# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0033_quickorder_internal_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'новый'), ('processing', 'оплачен'), ('success', 'отменен'), ('error', 'завершен')], default='new', max_length=16, verbose_name='Статус заказа')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Финальная сумма')),
                ('fns_site', models.CharField(max_length=256, verbose_name='Сайт')),
                ('fn_number', models.CharField(blank=True, max_length=256, null=True, verbose_name='Номер чека?')),
                ('shift_number', models.IntegerField(blank=True, null=True, verbose_name='shift_number')),
                ('receipt_datetime', models.DateTimeField(blank=True, null=True, verbose_name='receipt_datetime')),
                ('fiscal_receipt_number', models.IntegerField(blank=True, null=True, verbose_name='fiscal_receipt_number')),
                ('fiscal_document_number', models.IntegerField(blank=True, null=True, verbose_name='fiscal_document_number')),
                ('ecr_registration_number', models.CharField(blank=True, max_length=32, null=True, verbose_name='ecr_registration_number')),
                ('fiscal_document_attribute', models.CharField(blank=True, max_length=32, null=True, verbose_name='fiscal_document_attribute')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='orders.Order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name_plural': 'Чеки в Онлайн-кассе Счетмаш',
                'verbose_name': 'Чек в Онлайн-кассе Счетмаш',
                'ordering': ['-create_date'],
            },
        ),
    ]
