# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinekassa', '0002_auto_20180626_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='ticket_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='id заявки'),
        ),
    ]
